services:
  - type: web
    name: nasa-ultra-v5-autonomic
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 NASA_ULTRA_KIRA_AUTONOMIC_FINAL_V3.2.py"
